### ISSUE TITLE
is there a way to troubleshoot plugin?

### ISSUE THREAD

**Issue by youanswer** [couchmate/TeamCity-Phabricator-Plugin#3]
hello!
Thanks for pushing to TeamCity integration with Phabricator.
I've got a trouble with triggering the CI. 
`arc diff` successfully creates buildable, but 'Build with TeamCity' build step is being stuck in 'pending' state. I provided url and credentials to access TeamCity's REST along with build configuration ID which I took from here: _https://teamcityURL/httpAuth/app/rest/buildTypes_
It seems like Harbormaster does it job sending request, but Teamcity doesn't accept it for some reason.
TeamCity agent logs are clear, everything remains silent. Is there a way to check what's being triggered on teamcity server with this request? 
Or maybe it would be cool to have a "check connection" button inside teamcity plugin, similar to configuration when you set up VCS for a project. (feature request)
Thank you.

**Comment by halfmatthalfcat** [comment]
Hey @youanswer, can you post a screenshot of the http call output from Harbormaster for the build you ran?

**Comment by youanswer** [comment]
@halojedi20 
I couldn't find any http call output, tried to listen to the port with sysdig, but seems like it crashes even before sending anything.
I'm running phabricator inside docker container. 
This is the output of manually triggered build with URI of TeamCity server with https:

```
root@562d21d4f69a:/opt/phabricator# ./bin/harbormaster build D152 --plan 2
Applying plan 2 to new buildable B311...

    https://MyPhabricatorURL/B311

[2015-12-07 13:32:37] EXCEPTION: (Exception) URI 'https://MyTeamCityURL/httpAuth/app/rest/buildQueue' must be fully qualified with 'http://' scheme. at [<phutil>/src/future/http/HTTPFuture.php:50]
arcanist(), phabricator(custom=2), phutil()
  #0 <#2> HTTPFuture::setURI(string) called at [<phutil>/src/future/http/BaseHTTPFuture.php:47]
  #1 <#2> BaseHTTPFuture::__construct(string, string) called at [<phabricator>/src/extensions/HarbormasterTeamCityBuildStepImplementation.php:63]
  #2 <#2> HarbormasterTeamCityBuildStepImplementation::execute(HarbormasterBuild, HarbormasterBuildTarget) called at [<phabricator>/src/applications/harbormaster/worker/HarbormasterTargetWorker.php:52]
  #3 phlog(Exception) called at [<phabricator>/src/applications/harbormaster/worker/HarbormasterTargetWorker.php:81]
  #4 PhabricatorWorker::scheduleTask(string, array) called at [<phabricator>/src/applications/harbormaster/engine/HarbormasterBuildEngine.php:84]
  #5 HarbormasterBuildEngine::continueBuild() called at [<phabricator>/src/applications/harbormaster/worker/HarbormasterBuildWorker.php:25]
  #6 HarbormasterBuildWorker::doWork() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:117]
  #7 PhabricatorWorker::scheduleTask(string, array) called at [<phabricator>/src/applications/harbormaster/storage/HarbormasterBuildable.php:157]
  #8 HarbormasterBuildable::applyPlan(HarbormasterBuildPlan) called at [<phabricator>/src/applications/harbormaster/management/HarbormasterManagementBuildWorkflow.php:87]
  #9 HarbormasterManagementBuildWorkflow::execute(PhutilArgumentParser) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:406]
  #10 PhutilArgumentParser::parseWorkflowsFull(array) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:301]
  #11 PhutilArgumentParser::parseWorkflows(array) called at [<phabricator>/scripts/setup/manage_harbormaster.php:21]
Done.
```

This is what happens if I turn off HTTPS:

```
root@562d21d4f69a:/opt/phabricator# ./bin/harbormaster build D152 --plan 2
Applying plan 2 to new buildable B312...

    https://MyPhabricatorURL.com/B312

PHP Fatal error:  Call to undefined method HarbormasterTeamCityBuildStepImplementation::resolveFutures() in /opt/phabricator/src/extensions/HarbormasterTeamCityBuildStepImplementation.php on line 78

Fatal error: Call to undefined method HarbormasterTeamCityBuildStepImplementation::resolveFutures() in /opt/phabricator/src/extensions/HarbormasterTeamCityBuildStepImplementation.php on line 78
```

**Comment by halfmatthalfcat** [comment]
Ok so at this moment, the Phabricator Build Step only supports http (my implementation only uses http, so this is a limitation I build into it but should be rectified). Phabricator uses it's on future library for executing http calls that has both http and https implementations. I'm not sure why it doesn't work when turning off https but my guess is something is still blowing up using the http future implemention.

**Comment by halfmatthalfcat** [comment]
Limitation is here: https://github.com/couchmate/TeamCity-Phabricator-Plugin/blob/master/release/v1.0/HarbormasterTeamCityBuildStepImplementation.php#L63

**Comment by halfmatthalfcat** [comment]
If you can still access your teamcity via http://yourteamcity.com then you may be able to get it to work.

**Comment by youanswer** [comment]
@halojedi20 I've updated phabricator(I think it can be useful to add to readme this step), and checked out the repo since you've merged the PR for https from TeamCity, and it started to trigger builds. 
But I've experienced another problem: seems like if there was a newer commit to a diff, it doesn't get pulled by CI. Build is being run against first commit. Will try another diff to verify this and report back

**Comment by halfmatthalfcat** [comment]
If you update a diff, harbormaster should send that new commit to teamcity to build. Check if the builds are queuing correctly in teamcity.

**Comment by youanswer** [comment]
@halojedi20 It triggers the build, but seems like it pulls updates only from the default branch, `arc patch D123` is not being triggered on agent. But if I run manually arc patch inside agent, it works. I provided correct path for arcanist. If I could use Diff Id in the build step, I could run arc patch manually, but seems like it's not exposed there...

**Comment by halfmatthalfcat** [comment]
so it will always pull master and apply the patch over master. check the agent logs, there is output there on whether the plugin is enabled or not. if it's enabled yet there are errors, it will display them there. it will also print out all the variables used by the plugin and you'll be able to determine what you're missing.

**Comment by youanswer** [comment]
The problem was that arcanist on agent was using Conduit token of another user, not the one I've used in Phabricator plugin in teamcity. Also had some permissions issues on agent.
SO, to answer my original question, to troubleshoot Phabricator side test the plan you've created in Harbormaster by running `./bin/harbormaster build <Diff> --plan <planId>`

To troubleshoot TeamCity side, check teamcity-agent.log of your agent. Look for `Phabricator Plugin` exit codes. If it crashes on arc patch, try to run it manually on agent with `--trace` flag for more info. 

@halojedi20 thanks for support
